import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
  containerGeral: {
    flex: 1,
    backgroundColor: '#18212A',
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 20,
  },
  title: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 20,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 24,
  },
  subTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#ffffff',
    marginBottom: 5,
  },
  containerBoxSelect: {
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#C9A64D",
    backgroundColor: "#1E2A38",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
  },
  boxServiceTitle: {
    color: "#ffffff",
    fontSize: 16,
  },
  boxServicePrice: {
    color: "#C9A64D", 
    fontSize: 16, 
  },
  barberImage: {
    width: 50,
    height: 50,
    backgroundColor: "#dddddd",
    borderRadius: 100,
  },
  buttonText: {
    color: '#ffffff',
    fontFamily: 'Poppins_400Regular',
  },
  buttonAgendar: {
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#3CB371',
    borderRadius: 10,
  },
  containerBoxHorarios: {
    marginBottom: 24,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  horarioButton: {
    width: '22%',
    paddingVertical: 10,
    backgroundColor: '#1E2A38',
    borderColor: '#C9A64D',
    borderWidth: 1,
    borderRadius: 6,
    alignItems: 'center',
  },
  horarioText: {
    color: "#C9A64D",
  },
  containerBoxData: {
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  buttonData:{
    backgroundColor: '#1E2A38',
    borderColor: '#C9A64D',
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: '23%',
    paddingVertical: 10,
  },
  buttonDataSeccond:{
    backgroundColor: '#1E2A38',
    borderColor: '#C9A64D',
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: '50%',
    paddingVertical: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    backgroundColor: '#50687F',
    borderRadius: 12,
    padding: 20,
  },
  modalContainerBarbers: {
    padding: 15,
    alignItems: 'center',
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent:'center',
  },
  buttonsModalBarber:{
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    height: 120,
    backgroundColor: "#3C4E62",
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: "#C9A64D",
  },
  modalBarberText:{
    color: "#ffffff",
    fontSize: 14,
    paddingTop: 8,
    textAlign: "center",
    lineHeight: 18,
  },
  subTitleModal: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
    color: '#ffffff',
    textAlign: 'center',
  },
  containerBoxBarberSecundario: {
    flexDirection: "row",
    alignItems: "center",
  },
  containerBoxBarber: {
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#C9A64D",
    backgroundColor: "#1E2A38",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  boxBarberText: {
    color: "#ffffff",
    fontSize: 16,
    paddingLeft: 15,
  },
  dateHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectedDateText: {
    color: '#C9A64D',
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
  },
  buttonDataSelected: {
    backgroundColor: '#C9A64D',
  },
  buttonDataText: {
    color: '#C9A64D',
  },
  buttonDataTextSelected: {
    color: '#18212A',
  },
  noTimeText: {
    color: '#FFFFFF',
    textAlign: 'center',
    marginVertical: 24,
    fontSize: 16,
    fontFamily: 'Poppins_400Regular'
  },
  horarioButtonSelected: {
    backgroundColor: '#C9A64D',
  },
  horarioTextSelected: {
    color: "#18212A",
  },
  modalContentErro: {
    backgroundColor: '#50687F',
    padding: 20,
    borderRadius: 20,
    minHeight: '30%',
    justifyContent: 'center',
  },
  modalTitleErro: {
    fontSize: 18,
    fontFamily: 'Poppins_700Bold',
    marginBottom: 10,
    color: '#C70039',
  },
  modalText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#ffffff',
    marginBottom: 24,
  },
  buttonContainer: {
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#C9A64D',
    marginBottom: 24,
    borderRadius: 10,
  },
  buttonTextModal: {
    color: '#18212A',
    fontFamily: 'Poppins_400Regular',
  },
  modalTextGood: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 18,
    color: '#E1E1E1',
    fontWeight: 'bold',
  },
  checkIcon: {
    marginBottom: 15,
  },
  modalContentGood: {
    backgroundColor: '#262626',
    padding: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    borderWidth: 1,
    width: '100%',
  },
});

export default styles